#!/usr/bin/env python3
"""Build TODO watchlist from fetched MetaBBO candidates."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
from collections import defaultdict
from typing import Any


def read_jsonl(path: str) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def normalize_title(title: str) -> str:
    return re.sub(r"\s+", " ", title.lower()).strip()


def extract_arxiv_ids(text: str) -> set[str]:
    pattern = re.compile(r"arxiv\.org/(?:abs|pdf)/([0-9]{4}\.[0-9]{4,5})(?:v\d+)?", re.IGNORECASE)
    return set(pattern.findall(text))


def extract_titles(text: str) -> set[str]:
    pattern = re.compile(r"-\s+\*\*(.+?)\*\*")
    return {normalize_title(m.group(1)) for m in pattern.finditer(text)}


def read_text(path: str) -> str:
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return ""


def build_todo(rows: list[dict[str, Any]], output: str) -> None:
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        grouped[row.get("priority", "P3")].append(row)

    def fmt_item(item: dict[str, Any]) -> list[str]:
        tags = ", ".join(item.get("suggested_tags", []))
        paradigms = ", ".join(item.get("learning_paradigms", []))
        tasks = ", ".join(item.get("meta_tasks", []))
        q = "; ".join(item.get("matched_queries", [])[:2])
        return [
            f"- [ ] **{item['title']}**",
            f"  - Source: arXiv {item['published'][:10]} [[Link]]({item['url']})",
            f"  - arXiv ID: `{item['arxiv_id']}`",
            f"  - Suggested tags: {tags}",
            f"  - Meta task: {tasks} | Paradigm: {paradigms} | Problem: {item.get('problem_type', 'Other')}",
            f"  - Matched queries: {q}",
        ]

    lines = [
        "# TODO",
        "",
        "MetaBBO paper reading queue generated by `metabbo-research-tracker`.",
        "",
        f"Generated at: {now}",
        f"Candidate count: {len(rows)}",
        "",
    ]

    for priority in ["P1", "P2", "P3"]:
        items = grouped.get(priority, [])
        if not items:
            continue
        lines.extend([f"## {priority}", ""])
        for item in items:
            lines.extend(fmt_item(item))
            lines.append("")

    with open(output, "w", encoding="utf-8") as f:
        f.write("\n".join(lines).rstrip() + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Build TODO watchlist from MetaBBO candidate JSONL.")
    parser.add_argument("--input-jsonl", required=True, help="Input JSONL from fetch_arxiv_metabbo.py")
    parser.add_argument("--readme", default="README.md", help="README used for de-duplication")
    parser.add_argument("--output", default="TODO.md", help="Output TODO markdown path")
    parser.add_argument("--limit", type=int, default=40, help="Max number of candidates to keep")
    args = parser.parse_args()

    rows = read_jsonl(args.input_jsonl)
    rows.sort(key=lambda x: x.get("published", ""), reverse=True)

    readme_text = read_text(args.readme)
    existing_ids = extract_arxiv_ids(readme_text)
    existing_titles = extract_titles(readme_text)

    filtered: list[dict[str, Any]] = []
    for row in rows:
        if row.get("arxiv_id") in existing_ids:
            continue
        if normalize_title(row.get("title", "")) in existing_titles:
            continue
        filtered.append(row)
        if len(filtered) >= args.limit:
            break

    build_todo(filtered, args.output)

    print(
        "input=%d existing_ids=%d existing_titles=%d output=%d file=%s"
        % (len(rows), len(existing_ids), len(existing_titles), len(filtered), args.output)
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
